trading_bot:
  test_mode: false  # use exchanges testnet api
  exchange:
    options:
      - binance
      - kraken
    selected: binance
  base_currency:
    options:
      - eur
      - usd
      - btc
      - eth
    selected: usd
  base_symbol:  # symbol used to buy the index
    options:
      - busd
      - usdc
      - usdt
      - usd
    selected: busd
  savings_plan:
    cost: 500  # denoted in base_currency
    interval:  # still hardcoded right now
      options:
        - daily
        - weekly
        - biweekly
        - monthly
      selected: daily
  portfolio:
    mode:
      options:
        - cherry_pick
        - index  # not yet implemented
      selected: cherry_pick
    cherry_pick:
        symbols:
          - btc
          - eth
          - ada
          - dot
          - link
          - vet
          - sol
          - neo
          - matic
          - atom
          # - theta # not available on binance
          - avax
          - iota
          - xch
          - algo
          - one
          - qtum
          - nano
    index:
      top_n: 10
      exclude_symbols: [xrp]
    weighting:
      options:
        - equal
        - market_cap
        - sqrt_market_cap       # square root of market cap
        - cbrt_market_cap       # cubic root
        - sqrt_sqrt_market_cap  # fourth root
      selected: cbrt_market_cap

telegram_bot:

