version: "2"
services:
  fundless:
    container_name: fundless
    image: fundless
    build: .
    restart: unless-stopped
    volumes:
      - .:/code
    ports:
      - "80:80"
    environment:
      - TZ=Europe/Berlin
