from datetime import datetime
from typing import Annotated

from pydantic import computed_field
from sqlmodel import UUID, Field, SQLModel

from fundless.config import ExchangeEnum


class Order(SQLModel, table=True):
    # this ID must be set during creation
    id: Annotated[UUID, Field(primary_key=True)]
    symbol: str
    data: datetime


class TradeBase(SQLModel):
    date: datetime
    buy_symbol: str
    sell_symbol: str
    price: float
    amount: float
    fee: float = Field(default=0.0)
    fee_symbol: str | None = Field(default=None)
    cost_usd: float
    cost_eur: float
    exchange: ExchangeEnum

    @computed_field
    @property
    def cost(self) -> float:
        return self.price * self.amount

    @computed_field
    @property
    def cost_total(self) -> float:
        return self.cost + self.fee


class Trade(TradeBase, table=True):
    # this ID is auto-generated by the DB
    id: int | None = Field(default=None, primary_key=True, unique=True)


class TradeCreate(TradeBase):
    pass
